### PR TITLE
Rust cleanups

### PR DESCRIPTION
**Pull request by oowekyala**
While writing my thesis it occurred to me that the name mangling strategy used by the rust generator doesn't work.

I'd like to keep this PR open until after I finish my thesis, that way I can add minor fixes like this

### CODE REVIEW

**Comment by cmnrd** [comment]
@oowekyala could you comment on the state of this PR? Should we get this merged?

**Comment by oowekyala** [comment]
@cmnrd I think it should get merged. I'll look into the failing build, maybe it just needs merging master once more

**Review by cmnrd — APPROVED** [review]
Looks good. I was able to fix the compile issue. Also, I merged in master. I will merge this if all the tests pass.

**Comment by oowekyala** [comment]
@cmnrd thanks :)

**Pull request merged**
