### PR TITLE
Bugfix in integration tests and fixed ROS2 tests 

### PR DESCRIPTION
**Pull request by cmnrd**
This PR fixes a bug in our integration tests that prevented the C++ ROS2 tests from actually being compiled with the ROS2 flag. Effectively, we did not run any of the ROS2 tests for a while. Since a few small bugs crept into the ROS2 support in the meantime, this PR also fixes the problems in the ROS2 code generation and pulls in https://github.com/lf-lang/reactor-cpp/pull/50.

### CODE REVIEW

**Comment by cmnrd** [comment]
@erlingrj It looks like the fix in the test suite also exposed a bug in the zephyr support (see the test log). Could you take a look at this?

**Comment by cmnrd** [comment]
Ok, I think I wound the problem.

**Comment by erlingrj** [comment]
Will take a look tomorrow!

**Review by lhstrh — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by erlingrj** [comment]
Do we need a new type of Configurator which can modify the target properties and runs last?

**Comment by cmnrd** [comment]
Oh, that is a good point. Thanks! I guess it was not well-defined how the configurator is supposed to be used. The configurator for the ROS2 tests was modifying the resource, so that the target config needs to be reloaded after the transformation. I will change the ROS2 generator to also directly modify the target properties.

**Comment by lhstrh** [comment]
> Oh, that is a good point. Thanks! I guess it was not well-defined how the configurator is supposed to be used. The configurator for the ROS2 tests was modifying the resource, so that the target config needs to be reloaded after the transformation. I will change the ROS2 generator to also directly modify the target properties.

I had assumed that the added reload happened in between runs, but if it happens after the target property changes and before the execution, then that's no bueno.

**Pull request merged**
