### PR TITLE
Added support for C methods

### PR DESCRIPTION
**Pull request by edwardalee**
I've added support for methods in C because I need this to implement LET.
The invocation of a method in target code is a bit awkward.
You have to do this:
```
    self->my_method(self, my_arguments);
```
But with this design, method names need not be unique across reactors.

### CODE REVIEW

**Comment by Soroosh129** [comment]
There is an alternative way to do this using `#define` and `#undef` within the body of reactions.
```C
foo_reaction_function_1(...) {
    #define my_method(var1, var2) foo_my_method(self, var1, var2)

    #undef my_method
}
```

This would make the syntax for accessing methods slightly different though from the syntax for accessing state variables.

**Comment by edwardalee** [comment]
Great idea!  I will do this.

**Comment by lhstrh** [comment]
I personally don't find using the self struct to find a method all that awkward. In fact, that's were I would look for them given that's where state variables live...

**Review by Soroosh129 — APPROVED** [review]
Looks great!

**Pull request merged**
