### PR TITLE
Top level multiports for `remove-unordered-reactions`

### PR DESCRIPTION
**Pull request by petervdonovan**
This is still a work in progress. I expect to be working in this branch for some more days. It is not ready for review.

### CODE REVIEW

**Comment by petervdonovan** [comment]
17/57 tests passing now. A few days ago only 5 or 10 tests were passing, so maybe this is progress.

Right now ChainWithDelay is failing because the InternalDelay reactor, `i`, runs out of work on its earliest level before it has had a chance to enqueue the network receivers, which are inserted into the current level in response to a tagged message received over the network. The workers think that they are already done with the level, so the network receiver for time 0 just doesn't get executed. I am still working on a fix for this.

**Comment by petervdonovan** [comment]
Now [`DistributedNetworkOrder`](https://github.com/lf-lang/lingua-franca/blob/master/test/C/src/federated/DistributedNetworkOrder.lf) is failing, but I'm not sure that this is a test that we should keep. It tests an internal API, but the real reason why I am not sure we should keep it is that it tests a behavior that we plan to remove: https://github.com/lf-lang/lingua-franca/issues/1464

**Comment by petervdonovan** [comment]
### Status update:

Programs with physical actions deadlock. For example:
- DistributedCountPhysical deadlocks
- DistributedCountPhysicalAfterDelay also deadlocks
- DistributedLoopedPhysicalAction deadlocks on termination
- DistributedPhysicalActionUpstream deadlocks, probably on termination

Programs that use decentralized coordination seem to deadlock. For example:
- DistributedToken (which uses decentralized coordination) seems to deadlock on termination
- PhysicalSTP (decentralized) fails. Message violates STP offset. Deadlock
- STPParameter (decentralized) deadlocks on shutdown

Programs with federate-level cycles all seem to deadlock

StopAtShutdown deadlocks on termination and might be the only centralized program without federate-level cycles that deadlocks

**Comment by lhstrh** [comment]
> Now [`DistributedNetworkOrder`](https://github.com/lf-lang/lingua-franca/blob/master/test/C/src/federated/DistributedNetworkOrder.lf) is failing, but I'm not sure that this is a test that we should keep. It tests an internal API, but the real reason why I am not sure we should keep it is that it tests a behavior that we plan to remove: #1464

I agree that it seems reasonable to just remove this test...

**Comment by petervdonovan** [comment]
### Status update:

- 43/57 C federated tests are passing
- I think that all of the tests that are currently failing involve federate-level cycles

**Comment by lhstrh** [comment]
> ### Status update:
> 
>     * 43/57 C federated tests are passing
> 
>     * I think that all of the tests that are currently failing involve federate-level cycles

Wow, that's really encouraging!

**Pull request merged**
