### PR TITLE
Add RPi pico support for v0.7

### PR DESCRIPTION
**Pull request by erlingrj**
The RPi pico support needs updates to support v0.7. In this PR I make a few minor changes needed. I have not setup the pico toolchain locally so haven't tested it. See: https://github.com/lf-lang/lingua-franca/issues/2282 Maybe @sberkun can follow up on it? 

Would be great with a simple CI test that at least builds a hello world to avoid this in the future. Do you have any estimate of how hard that would be Samuel?

### CODE REVIEW

**Comment by sberkun** [comment]
Sorry for the delay! Following some recent changes (splitting the runtime into many CMake modules), the libraries need to be added to `lf-low-level-platform-api` as well as `reactor-c`. https://github.com/lf-lang/reactor-c/pull/344 addresses `lf-low-level-platform-api` and this PR (or #2178) addresses `reactor-c`.

Setting up a compilation test should be doable, the main steps are:
 - install GCC cross compiler (see [raspberrypi documentation](https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html#quick-start-your-own-project))
 - clone the sdk
 - set PICO_SDK_PATH environment variable
 - compile (but not run) a hello-world test
I'm not familiar with how the automated tests are set up, but I imagine this could be accomplished by copying the Ubuntu tests and adding a few lines.

**Review by sberkun — APPROVED** [review]

**Comment by edwardalee** [comment]
Looks like this change is also included in #2178, so I think this can be safely be closed.

**Comment by lhstrh** [comment]
> Looks like this change is also included in #2178, so I think this can be safely be closed.

@sberkun, could you confirm this?

**Comment by lhstrh** [comment]
Given the lack of response I'm assuming it's safe to close this.

**Pull request closed without merging**
