### PR TITLE
Update `fedsd` utility to make the RTI optional and support enclaves visualization 

### PR DESCRIPTION
**Pull request by ChadliaJerad**
This PR updates `fedsd` utility to not require an RTI trace file.
This is per @erlingrj 's request, so that it supports enclaves visualization.

### CODE REVIEW

**Comment by ChadliaJerad** [comment]
@erlingrj and @edwardalee, this PR is intended to adapt `fedsd` to visualize the interactions between enclaves.
To this end, it derives the RTI tracepoints and draws horizontal lines for the communications.
The figure below showcases the output from a federation visualization, without using `rti.lft`.
fed_like_enclave

Does this make sense?

**Comment by edwardalee** [comment]
Ah, cool!But there is still the issue that all the trace points will go into one file.It also could be a real can of worms if we try to visualize federates with enclaves.Edward---------Edward A. LeeEECS, UC ***@***.***://eecs.berkeley.edu/~ealOn Jun 27, 2023, at 7:11 PM, Chadlia Jerad ***@***.***> wrote:﻿
@erlingrj and @edwardalee, this PR is intended to adapt fedsd to visualize the interactions between enclaves.
To this end, it derives the RTI tracepoints and draws horizontal lines for the communications.
The figure below showcases the output from a federation visualization, without using rti.lft.

Does this make sense?

**Comment by erlingrj** [comment]
Hi @ChadliaJerad, thanks alot for looking at this. I am currently getting a diagram that looks like this:
image

Based on the following 2 trace files (renamed from `.lft` to `.txt` to enable upload to Github):
[EnclaveTracing_wrapper_src.txt](https://github.com/lf-lang/lingua-franca/files/11892227/EnclaveTracing_wrapper_src.txt)
[EnclaveTracing.txt](https://github.com/lf-lang/lingua-franca/files/11892226/EnclaveTracing.txt)

It would be amazing if we could get the the TAGGED_MSG event to go directly between the two enclaves. I think it is quite doable. All the messages that go to/from the RTI have dest/src  `-1` while this TAGGED_MSG has src and dest set to the enclave ids

**Comment by erlingrj** [comment]
I added to minor changes.
1. Improve the exeception handling in fedsd 
2. Make the `fedsd` script use the `trace_to_csv` utility that is within the same bin directory as `fedsd`. It was currently using whichever was on the path and for me there was another `trace_to_csv` executable on the path

**Comment by erlingrj** [comment]
@edwardalee initially we will just use it draw diagrams of the enclaves coordination. I haven't even thought about Diagrams for enclaved federations yet. I think it could make sense to have one process per enclave and one process for the RTI process within each enclave. Those RTI processes will be the ones exchanging federate-level NETs and LTCs

**Comment by ChadliaJerad** [comment]
> > Ah, cool!But there is still the issue that all the trace points will go into one file.It also could be a real can of worms if we try to visualize federates with enclaves.
> 
> Indeed. Currently, the diagrams that make sense are either for federations or enclaves. As mentioned by @erlingrj, the adaptation is just a step to help understand enclaves interactions. Enclaved federates need to be thought toughly. This can only be done once the coordination federates/enclaves remote_rti/local_rti are set.

BTW @edwardalee, there is a trace file per enclave.

**Comment by erlingrj** [comment]
I am using federate_to_federate but still the arrow goes to the RTI.

**Comment by ChadliaJerad** [comment]
> I am using federate_to_federate but still the arrow goes to the RTI.

I see why. I will fix it right now (and check with your  trace files) and let you know.

**Comment by ChadliaJerad** [comment]
@erlingrj, here is the diagram after the fix (using the trace files you provided):
image

**Comment by erlingrj** [comment]
Thats great! Very useful!

**Review by erlingrj — APPROVED** [review]
LGTM!

**Pull request merged**
