### PR TITLE
Auhenticated federation fixed

### PR DESCRIPTION
**Pull request by Jakio815**
This resolves lf-lang/lingua-franca#1666.

Please merge together with lf-lang/reactor-c#196.

### CODE REVIEW

**Comment by Jakio815** [comment]
@petervdonovan Hi Peter. I really don't understand what's the problem and asking you for some insights.

The problem is the CI test runner can't find openssl headers, when making federate binaries.

The problem is this part.

```
/Users/runner/work/lingua-franca/lingua-franca/test/C/fed-gen/SimpleFederatedAuthenticated/src-gen/fed1/core/federated/federate.c:65:10: fatal error: 'openssl/rand.h' file not found
```

and I see it's happening when the `make` command occurs. But I don't understand why it's not working, because the CMake's OpenSSL linking has worked above. Also, the RTI build also works which also needs openssl headers.

I really don't know why it's not working. I have a bunch of tries on my commits, so you may check it out if the CI test takes too long.

I hope for your help!

**Comment by petervdonovan** [comment]
It looks like you're doing basically the right things here, and I do not know off the top of my head what the issue is likely to be. However, here are some ideas:
* where you write `if (osName.contains("mac")) {` in CMakeLists.txt, make sure that it isn't returning `darwin`, or something like that, instead of `mac`. You can add debug prints to the CMakeLists.txt if you need to in order to check that the branch is being executed.
* You can also try to SSH into the GitHub Actions runner. This is surprisingly easy and is briefly mentioned [here](https://github.com/lf-lang/lingua-franca/blob/009d9f404a04f27701303aa9b5e41d7b043bbe55/.github/workflows/README.md#debugging-tests).

**Comment by Jakio815** [comment]
Wow. Never knew I could ssh into the runner. I'll try that! Thanks!

**Comment by Jakio815** [comment]
@lhstrh  It's finally ready. Thanks to @petervdonovan telling me the ssh trick!

**Review by lhstrh — APPROVED** [review]
Looks good! Thanks for fixing this :+1:

**Comment by Jakio815** [comment]
@lhstrh Please merge this together with lf-lang/reactor-c#196.

**Pull request merged**
