### PR TITLE
Fix to generate launch script for TS target and print informational message

### PR DESCRIPTION
**Pull request by hokeun**
This fixes https://github.com/lf-lang/lingua-franca/issues/1986.

Also did a minor code cleanup.

### CODE REVIEW

**Review by edwardalee — APPROVED** [review]
LGTM.

**Review by lhstrh — CHANGES_REQUESTED** [review]
This looks great and it works well, but I have some suggestions for improvement:
 - don't just print the directory but print the full path of the executable
 - adjust the "Generating launcher for federation" message to do the same

**Comment by hokeun** [comment]
> * adjust the "Generating launcher for federation" message to do the same

Could you elaborate on this? I'm not sure what you meant by "do the same."

**Comment by lhstrh** [comment]
> > * adjust the "Generating launcher for federation" message to do the same
> 
> Could you elaborate on this? I'm not sure what you meant by "do the same."

Sorry for not being clear. I just pushed a fix here because it was quicker than trying to clarify :smile: 

See https://github.com/lf-lang/lingua-franca/pull/2090/commits/b6eba5f6b995a407e33e25f17762b544b9859d3e

**Review by lhstrh — APPROVED** [review]

**Pull request merged**
