### PR TITLE
Zero-width multiports

### PR DESCRIPTION
**Pull request by petervdonovan**
This PR fixes zero-width multiports for the C target.

### CODE REVIEW

**Review by edwardalee — APPROVED** [review]
LGTM!  Thanks for doing this.

**Comment by cmnrd** [comment]
What is the motivation for using zero width multiports? And what exactly does this PR fix?

**Comment by petervdonovan** [comment]
> What is the motivation for using zero width multiports? And what exactly does this PR fix?

In our conversation about mutations, I started making unsubstantiated claims that we could have a lot of expressive power using other means. This prompted me to write some weird programs in the experimental repo. Among these was [this one](https://github.com/lf-lang/experimental-lingua-franca/blob/composition/C/src/Composition/Hypercube.lf), which had issues with connections not being made and with wrong error messages that there were more sources than destinations in a connection and vice versa due to its zero-width multiports. I wanted zero-width multiports because they are necessary in order to continue a pattern across a set of similar reactors. I wanted to continue a pattern across a set of similar reactors so that I could argue that those similar reactors should all be generated from the same source code.

**Comment by petervdonovan** [comment]
I'm not seeing the light at the end of the tunnel on this one. Let's shelve this until we know the future of `initialize_trigger_objects` and the other complex code that operates on the exploded reactor instance graph.

**Comment by lhstrh** [comment]
Closing this based on the last comment by @petervdonovan in this thread.

**Pull request closed without merging**
