### PR TITLE
Update kotlin version

### PR DESCRIPTION
**Pull request by oowekyala**
I was having trouble building, the kotlin compilation was failing with this error:
```
> Task :org.lflang:compileKotlin FAILED
e: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel
        at org.jetbrains.kotlin.com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
        at org.jetbrains.kotlin.com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:121)
        at org.jetbrains.ko
```

After some digging I found that our gradle wrapper uses kotlin 1.5.31:
```
$ ./gradlew --version
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
OS:           Linux 5.13.0-27-generic amd64
```

This PR updates the kotlin version we use to be in sync with that of gradle, which resolves the error for me.

### CODE REVIEW

**Review by cmnrd — COMMENTED** [review]
I updated this branch to use the kotlin version specified in gradle.properties.

Unfortunately, with Kotlin 1.5.31 the issue #935 appears again (this is the reason why we downgraded to 1.4.30). Essentially, if you run build-lfc twice, it will produce a jar without Kotlin classes (for whatever reason...). Maybe you can try again with Kotlin version 1.4.30 and setting the plugin version explicitly as in this change? Also, let me know if you have any ideas regarding the cause of #935.

**Comment by oowekyala** [comment]
@cmnrd Thanks for the review and context. I can't reproduce the build failures I was experiencing... Maybe it was because of my jdk version 17, though today it works fine... :shrug: I guess we can just close this.

I'm not sure what to do about  the issue you're referring to (is it really #935?), but it sounds like a caching problem maybe?

**Comment by petervdonovan** [comment]
> I'm not sure what to do about the issue you're referring to

(I think he probably meant #928 and #930.)

**Comment by cmnrd** [comment]
Yes, that's what I meant. Not sure what happened there with the numbers :laughing:

**Pull request closed without merging**
