### PR TITLE
Modal multiport

### LINKED ISSUE #2418: Modal Modes - Multiport reactors compilation error
```
target C;

reactor Destination (bank_index:int = 0, name:string = "DST", n_inputs:int = 1) {
    input [n_inputs] req:int;
    output [n_inputs] rsp:int;

    reaction (req) -> rsp {=
        for (int i = 0; i < self->n_inputs; ++i) {
            if (req[i]->is_present) {
                printf ("(%lld, %u) physical_time:%lld "
                        "%s [%d] Sending back response:%d\n",
                        lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                        self->name, self->bank_index, req[i]->value
                );
                lf_set (rsp[i], req[i]->value);
            }
        }
    =}
}

reactor Source (bank_index:int = 0, name:string = "Source") {
    output req:int;
    input rsp:int;

    state msg:int = 0;

    reaction (startup) -> req {=
        printf ("(%lld, %u) physical_time:%lld "
                "%s [%d] Scheduling request:%d\n",
                lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                self->name, self->bank_index, self->msg
        );
        lf_set (req, self->msg);
    =}

    reaction (rsp) {=
        printf ("(%lld, %u) physical_time:%lld "
                "%s [%d] Receiving response:%d\n",
                lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                self->name, self->bank_index, rsp->value
        );
    =}
}

reactor Selector (bank_index:int = 0, name:string = "Selector", n_ports:int = 1) {
    input [n_ports] in_req:int;
    output [n_ports] out_rsp:int;

    initial mode Init {
        reaction (startup) -> history (DST_1), history (DST_2) {=
            printf ("(%lld, %u) physical_time:%lld "
                    "%s POP startup",
                    lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                    self->name
            );
            lf_set_mode(DST_1);
        =}
    }

    mode DST_1 {
        dst1 = new Destination(name = "DST_1");

        in_req -> dst1.req;
        dst1.rsp -> out_rsp;
    }

    mode DST_2 {
        dst2 = new Destination(name = "DST_2");

        in_req -> dst2.req;
        dst2.rsp -> out_rsp;
    }
}



main reactor {
    src = new Source();
    sel = new Selector();

    src.req -> sel.in_req;
    sel.out_rsp -> src.rsp;
}
```

 mode DST_1 and mode DST_2 have multiport destination reactor that doesn't compile.

However, if we make destination reactor single port, compilation goes fine.

```
target C;

reactor Destination (bank_index:int = 0, name:string = "DST") {
    input req:int;
    output rsp:int;

    reaction (req) -> rsp {=
        printf ("(%lld, %u) physical_time:%lld "
                "%s [%d] Sending back response:%d\n",
                lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                self->name, self->bank_index, req->value
        );
        lf_set (rsp, req->value);
    =}
}

reactor Source (bank_index:int = 0, name:string = "Source") {
    output req:int;
    input rsp:int;

    state msg:int = 0;

    reaction (startup) -> req {=
        printf ("(%lld, %u) physical_time:%lld "
                "%s [%d] Scheduling request:%d\n",
                lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                self->name, self->bank_index, self->msg
        );
        lf_set (req, self->msg);
    =}

    reaction (rsp) {=
        printf ("(%lld, %u) physical_time:%lld "
                "%s [%d] Receiving response:%d\n",
                lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                self->name, self->bank_index, rsp->value
        );
    =}
}

reactor Selector (bank_index:int = 0, name:string = "Selector") {
    input in_req:int;
    output out_rsp:int;

    initial mode Init {
        reaction (startup) -> history (DST_1), history (DST_2) {=
            printf ("(%lld, %u) physical_time:%lld "
                    "%s POP startup",
                    lf_time_logical_elapsed(), lf_tag().microstep, lf_time_physical_elapsed(),
                    self->name
            );
            lf_set_mode(DST_1);
        =}
    }

    mode DST_1 {
        dst1 = new Destination(name = "DST_1");

        in_req -> dst1.req;
        dst1.rsp -> out_rsp;
    }

    mode DST_2 {
        dst2 = new Destination(name = "DST_2");

        in_req -> dst2.req;
        dst2.rsp -> out_rsp;
    }
}

main reactor {
    src = new Source();
    sel = new Selector();

    src.req -> sel.in_req;
    sel.out_rsp -> src.rsp;
}
```

### PR DESCRIPTION
**Pull request by edwardalee**
Modal models previously lacked support for multiports and banks.  This fixes that problem.
Closes issue #2418.

### CODE REVIEW

**Comment by Depetrol** [comment]
This looks good to me and solves the issue nicely. We might have to bump reactor-c again before merging, otherwise the newly introduced test in #2423 would fail.

**Review by Depetrol — APPROVED** [review]

**Comment by edwardalee** [comment]
The test failure here requires this merge: https://github.com/lf-lang/reactor-c/pull/490
which in turn requires this merge: https://github.com/lf-lang/lingua-franca/pull/2424

**Review by OmerMajNition — APPROVED** [review]
lgtm, I've tried with few tests, solves this particular problem

**Comment by lhstrh** [comment]
Note that the Python failure indicates a segfault...

**Comment by Depetrol** [comment]
This is related to the newly introduced test in https://github.com/lf-lang/lingua-franca/pull/2423. I'm actively investigating this concurrently bug (see [here](https://github.com/lf-lang/reactor-c/pull/490#issuecomment-2418024270)). Meanwhile, this test should be moved into failing.

**Comment by edwardalee** [comment]
> Note that the Python failure indicates a segfault...

It has always been the case that when a Python program fails, the main process segfaults. The segfault occurs after the failure, not before. It is really inelegant, but I haven't been able to figure out how to track it down.

**Pull request merged**
