### PR TITLE
Better multiport support for Rust

### PR DESCRIPTION
**Pull request by oowekyala**
This is the companion branch to lf-lang/reactor-rs#29.

### CODE REVIEW

**Comment by cmnrd** [comment]
Is this ready for review? From the rust benchmark test failure I assume this also needs to be accompanied by changes in the benchmark repo, right?

**Comment by oowekyala** [comment]
Thanks for the pointer, I had forgotten about that. I'll open a PR there

**Comment by jhaye** [comment]
Seems like this slightly changes the API for `ReactionCtx::get(…)`. The benchmarks should probably be adjusted accordingly.

**Review by cmnrd — APPROVED** [review]
This looks great! I can take care of merging the PRs in the different repos, as it requires a bit of care to keep everything in sync.

**Pull request merged**
