### PR TITLE
Scalability banks

### PR DESCRIPTION
**Pull request by edwardalee**
This branch, which still needs a lot of work, is a major redesign of the C generator and related infrastructure.  All the core C tests are passing for me. I'm creating a draft pull request so that we can figure out how to merge this with master, which I don't know how to do since master seems to have significantly refactored GeneratorBase and CGenerator.

### CODE REVIEW

**Comment by petervdonovan** [comment]
Apparently `ManualDelayedReaction` and `SlowingClockPhysical` are failing for the same reason why the "no CMake" tests were failing -- the use of `targetConfig` as shared state between `CGenerator` and `GeneratorBase`. Sorry about that. I am working on a fix.

**Comment by petervdonovan** [comment]
It is exciting to see the compilation time for Big go down from 1 hour on Wessel to about a second :tada:. Big, Chameneos, Banking, and SleepingBarber each seem to take only about a second to compile.

Execution times seem to have gone down in this branch for a few benchmarks although I do not understand why. For example, on Wessel, it looks like the execution time for LogisticMap decreased by 28% at commit 49b9bf0 in comparison to master (bcd2d8ca). Here are the data from Wessel: [summary.csv](https://github.com/lf-lang/lingua-franca/files/7884389/summary.csv).

**Comment by lhstrh** [comment]
Is this ready for review yet?

**Comment by edwardalee** [comment]
Yes. I still have a long to-do list and there are quite a few parts of the code that need help, but the scalability functionality is working. I will issue a regular pull request.

**Comment by lhstrh** [comment]
For future reference, you don't have to close the PR, you can just turn mark it as "ready for review," which turns it into a regular PR.

**Pull request closed without merging**
