### PR TITLE
Removal of PyDev and Kotlin plugin dependencies from Epoch

### PR DESCRIPTION
**Pull request by lhstrh**
Attempt to address code signing issues discussed in https://github.com/lf-lang/lingua-franca/issues/1173

### CODE REVIEW

**Comment by lhstrh** [comment]
@a-sr: having removed the Kotlin plugin is causing compile errors. Could we just introduce the dependency through Maven rather than Tycho?

**Comment by lhstrh** [comment]
Also tagging @oowekyala for help on this.

**Comment by a-sr** [comment]
> @a-sr: removal of the Kotlin plugin is causing compile errors in the Maven build. Could we just introduce the dependency through Maven rather than Tycho?

I am not sure if that is possible because Kotlin is a runtime dependency and Eclipse only accepts plugins in its runtime. We could try to pull the dependency via maven central and then put it on the plugin's classpath but I have the feeling that we already tried that in the past and it was problematic. One thing I am certain of is that it will complicate the build process in the Eclipse IDE because Eclipse does not like to mix maven and eclipse dependencies in the same project.
I hope the restructuring in #1276 will resolve the barriers in the future. However, the structure described there is not yet possible. I have to change the build process for the diagrams and the LDS first, and also have to find a workaround to get it working in an Eclipse plugin without problems on the classpath. It is definitely on my short-term Todo list but I currently do not have the time to tackle this.

**Comment by lhstrh** [comment]
OK, thanks for looking into this, @a-sr. It sounds like there is no way to properly support Epoch on macOS then, because code signing won't work if the Kotlin plugin is included, and building Epoch won't work without the Kotlin plugin.

**Comment by lhstrh** [comment]
Confirmed that this doesn't impair the code generators that are written in Kotlin.

**Pull request merged**
