### PR TITLE
Fix for cycle detection issue

### LINKED ISSUE #2033: Cycle detection erroneously reports cycles with physical connections
Consider this minimal program:
```
target C

reactor Foo {
  input in: void
  output out: void
  reaction(in)  -> out
}

reactor B {
  input in: void
  output out: void
  reaction(in)  -> out
}

main reactor Minimal {
  a = new Foo()
  b = new Foo()

  a.out ~> b.in
  b.out -> a.in
}
```
Notice the physical connection. The compiler (and diagram) reports a dependency cycle nonetheless. Interestingly, the physical connection gets not highlighted as part of the cycle (neither in the compiler output nor in the diagram).

### PR DESCRIPTION
**Pull request by lhstrh**
Fixes #2033.

### CODE REVIEW

**Comment by lhstrh** [comment]
Looks like the code I touched is also used for federation to figure out the topology. For cycle detection, a physical connection should break the cycle, which it does now, but it makes federated tests fail. Not sure how to address this. @edwardalee, could you take a look?

**Comment by edwardalee** [comment]
It is not surprising that this change would cause failures. It changes the semantics of the eventualDestinations method. I'm surprised there aren't unfederated failures. I also think that excluding connections with delays is suds. Maybe this is related to federated failures with multiport's and delays?

**Comment by lhstrh** [comment]
To me, it is surprising. This code is used for causality analysis in the validator. Maybe it should not be, but for that use, connections that are physical or have delay should not imply dependencies.

**Comment by edwardalee** [comment]
The `eventualDestinations` method comment says this:
```
   * Return a list of ranges of this port, where each range sends to a list of destination ports
   * that receive data from the range of this port. Each destination port is annotated with the
   * channel range on which it receives data. The ports listed are only ports that are sources for
   * reactions, not relay ports that the data may go through on the way. Also, if there is an
   * "after" delay anywhere along the path, then the destination is not in the resulting list.
```
I think your reasoning is that a physical connection is much like an `after` connection with an unspecified amount of delay. This is reasonable, so changing this method (and its description) is defensible, but it still means making sure that all uses still work.  If I had to guess, there is a place where this method is used to set `num_destinations`, and maybe this is being used in federated execution.

**Comment by byeong-gil** [comment]
@lhstrh I fixed the compile error due to the wrong TPO level assignment and added a test for this PR's change. Could you review it?

**Review by petervdonovan — APPROVED** [review]
I'm not aware of any way that these changes could cause problems. I think it's true that physical connections do not need to be addressed in TPO.

**Review by lhstrh — COMMENTED** [review]
This looks like the right solution to me!

**Pull request merged**
