### PR TITLE
Use nowhere() when reporting scheduler warnings

### LINKED ISSUE #2228: Specifying `-s=NP` or `-s=ADAPTIVE` on the command line crashes lfc when a program contains deadlines.
Here is how to reproduce it: `lfc-dev -s=NP test/C/src/Deadline.lf`. `NP` can be replaced with `ADAPTIVE` and the same behavior occurs. Here is my error trace:
```
$ lfc-dev -s=NP test/C/src/Deadline.lf
lfc: fatal error: An unexpected error occurred:
java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.InternalEObject.eProxyURI()" because "eObject" is null
        at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3058)
        at org.eclipse.xtext.validation.EObjectDiagnosticImpl.getUriToProblem(EObjectDiagnosticImpl.java:94)
        at org.lflang.cli.StandaloneIssueAcceptor.getPath(StandaloneIssueAcceptor.java:60)
        at org.lflang.cli.StandaloneIssueAcceptor.accept(StandaloneIssueAcceptor.java:46)
        at org.lflang.cli.StandaloneMessageReporter.reportOnNode(StandaloneMessageReporter.java:58)
        at org.lflang.MessageReporterBase.lambda$at$3(MessageReporterBase.java:48)
        at org.lflang.MessageReporterBase.lambda$wrap$0(MessageReporterBase.java:32)
        at org.lflang.MessageReporter$Stage2.warning(MessageReporter.java:95)
        at org.lflang.target.property.SchedulerProperty.validate(SchedulerProperty.java:67)
        at org.lflang.target.TargetConfig.lambda$validate$8(TargetConfig.java:400)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.lflang.target.TargetConfig.validate(TargetConfig.java:398)
        at org.lflang.target.TargetConfig.<init>(TargetConfig.java:144)
        at org.lflang.generator.MainContext.loadTargetConfig(MainContext.java:163)
        at org.lflang.generator.MainContext.<init>(MainContext.java:105)
        at org.lflang.cli.Lfc.invokeGenerator(Lfc.java:228)
        at org.lflang.cli.Lfc.doRun(Lfc.java:201)
        at org.lflang.cli.CliBase.run(CliBase.java:124)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.lflang.cli.CliBase.doExecute(CliBase.java:115)
        at org.lflang.cli.CliBase.cliMain(CliBase.java:107)
        at org.lflang.cli.Lfc.main(Lfc.java:189)
        at org.lflang.cli.Lfc.main(Lfc.java:179)
```

One observation is that the `NP` and `ADAPTIVE` scheduler has the `prioritizesDeadline` field set to `false` (this line in `SchedulerType.java`). When a program contains deadlines, `validate()` in SchedulerProperty.java:67 errors out.
```Java
reporter
            .at(config.lookup(this), Literals.KEY_VALUE_PAIR__VALUE)
            .warning(
                "This program contains deadlines, but the chosen "
                    + scheduler
                    + " scheduler does not prioritize reaction execution "
                    + "based on deadlines. This might result in a sub-optimal "
                    + "scheduling.");
```

The issue seems to be `.at(config.lookup(this), Literals.KEY_VALUE_PAIR__VALUE)`, since the scheduler property is passed in on the command, there is no corresponding EObject for the reporter.

### PR DESCRIPTION
**Pull request by lsk567**
This should fix #2228 .

### CODE REVIEW

**Comment by lhstrh** [comment]
Please don't use such insanely long branch names going forward :rofl:

**Review by lhstrh — COMMENTED** [review]
Looks like a reasonable fix to me...

**Comment by cmnrd** [comment]
This fix has the downside that `nowhere()` is also used when reporting on the normal target properties. I implemented a more general fir in this PR https://github.com/lf-lang/lingua-franca/pull/2230.

**Comment by lhstrh** [comment]
Subsumed by https://github.com/lf-lang/lingua-franca/pull/2230.

**Pull request closed without merging**
