### PR TITLE
Move tracing utils and zephyr run scripts from util folder

### PR DESCRIPTION
**Pull request by erlingrj**
Addresses #1946 and #1947. Mainly removing all the tracing related utilities from `lingua-franca/util` and instead putting them in `reactor-c`. We also install them to `/usr/local/bin` by default (together with the RTI) but allow overriding of this.

Related PRs:
Docs: https://github.com/lf-lang/lf-lang.github.io/pull/151
reactor-c: https://github.com/lf-lang/reactor-c/pull/259

### CODE REVIEW

**Comment by erlingrj** [comment]
This is ready for merge. The reason why some of the CI is still pending is that these tasks are moved to reactor-c. But the CI uses the ci.yml from master always so it will not take effect until it is merged.

@ChadliaJerad FYI we are moving the trace utils to reactor-c, Marten made me aware of that you are working on some of the tracing tools in another branch.

**Review by cmnrd — APPROVED** [review]
Thanks for addressing this @erlingrj!

I removed the tracing CI checks from the list of required checks.

**Comment by edwardalee** [comment]
Merging this into master without merging [reactor-c 259](https://github.com/lf-lang/reactor-c/pull/259) means that the tracing utilities are no longer available at all.  Can we reverse this merge until we are ready to merge both?

**Comment by ChadliaJerad** [comment]
> This is ready for merge. The reason why some of the CI is still pending is that these tasks are moved to reactor-c. But the CI uses the ci.yml from master always so it will not take effect until it is merged.
> 
> @ChadliaJerad FYI we are moving the trace utils to reactor-c, Marten made me aware of that you are working on some of the tracing tools in another branch.

Sure. I will handle this.

**Pull request merged**
