### PR TITLE
PowerShell scripts for lfc and lff

### PR DESCRIPTION
**Pull request by axmmisaka**
As mentioned in the commit message, this current implementation is very *NIX-y/bashy and not powershell-y. While I don‘t doubt its correctness this adds complications; maybe we should just pass the thing in as argument.

### CODE REVIEW

**Comment by axmmisaka** [comment]
There appears to be some misunderstanding until I saw this: https://github.com/lf-lang/lingua-franca/pull/1422#issuecomment-1293139385

**Review by cmnrd — CHANGES_REQUESTED** [review]
This looks great! While testing this I noticed one problem though. It seems like we cannot pass any additional arguments to lfc and lff anymore. For instance `.\bin\lfc.ps1 -c test\C\src\Minimal.lf` produces an error complaining that `test\C\src\Minimal.lf` does not exist. Do you have an idea what is going on here? It works perfectly fine without any additional arguments.

**Comment by axmmisaka** [comment]
Ah I see, my hypothesis is that PS takes `./bin` as its PWD… because running `.\bin\lfc.ps1 -c .\..\test\C\src\Minimal.lf`works.

**Comment by axmmisaka** [comment]
Unsure if using `.` or `Invoke-Command` would be better

**Review by lhstrh — APPROVED** [review]
Looks good to me! Thanks for fixing this :-)

**Comment by cmnrd** [comment]
Thanks @axmmisaka!

**Pull request merged**
