### PR TITLE
Formatted C++ examples for better readability

### PR DESCRIPTION
**Pull request by revol-xut**
# Formatting C++ Examples

**What did I change ?**
- the C++ examples had very inconsistent and irritating indentation. 
- removed trailing white spaces
- moved some code around
- added some extra lines where necessary

**What did I test ?**
- [x] successfully compiled and run every changed example except ROS where for some reason only the code generator was triggered without compiling the results.

### CODE REVIEW

**Review by lhstrh — CHANGES_REQUESTED** [review]
While I see that there were some indentation problems in the code, this PR seems to mostly reduce the indentation from four spaces to two. The rest of the code base (mostly) uses two. If you want to propose to change this convention, you could start a [discussion](https://github.com/lf-lang/lingua-franca/discussions) thread about this. Could you change it to 4-space indentation for the time being? We should also document this in our "contributing" document that is still being drafted. I'll make a note. Thanks!

**Comment by revol-xut** [comment]
Thanks for the advice @lhstrh. I changed it to use 4 spaces. 

It's just a little thing (indentation) but it bothered me while learning lingua franca. :D

**Review by lhstrh — APPROVED** [review]
Looks good! Thanks for the quick turnaround.

**Comment by cmnrd** [comment]
Thanks @revol-xut for cleaning that mess ;) In the past, Epoch used tabs for indentation which created this mess. We have it now configured to insert 4 spaces.

**Pull request merged**
