### PR TITLE
Replace sha256sum with shasum in CI actions

### PR DESCRIPTION
**Pull request by patilatharva**
I noticed that for any macOS CI action, in the Prepare Build Environment section there's an error that looks like
```
Run echo "gradle-hash"="$(find . -type f \( -name "gradle.properties" -o -name "gradle-wrapper.properties" \) -exec cat {} + | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_ENV
[56](https://github.com/lf-lang/lingua-franca/actions/runs/4669921848/jobs/8269011551#step:3:60)
/Users/runner/work/_temp/cf76cf63-b924-448a-9a60-8db61e686d90.sh: line 1: sha256sum: command not found
```
As a result of which all macOS build caches are stored and retrieved under the key `gradle-macOS-`, although it doesn't cause an error yet. This PR fixes the bug by replacing function `sha256sum` with `shasum`.

### CODE REVIEW

**Comment by lhstrh** [comment]
I just looked and it seems like the hash still doesn't work?

image

**Comment by patilatharva** [comment]
It says:
```
The agent pool assigned to this job has hit their MacOs concurrency limits
Requested labels: macos-latest
Job defined at: lf-lang/lingua-franca/.github/workflows/build-trace-tools.yml@refs/heads/master
Reusable workflow chain:
lf-lang/lingua-franca/.github/workflows/ci.yml@refs/pull/1690/merge (960b279789a55350dc9d08570b672db13a98b392)
-> lf-lang/lingua-franca/.github/workflows/build-trace-tools.yml@refs/heads/master (422d06f3f0d26cc10b3575e6b9ed20cc97726864)
Waiting for a runner to pick up this job...
```
I think it just hasn't run yet, we might have to wait for some time.

**Comment by lhstrh** [comment]
There is something strange happening with the hash, it looks like:

image

**Comment by lhstrh** [comment]
Also, there is still no Windows cache, so it doesn't look like it's being saved...

**Comment by lhstrh** [comment]
Here's a log that shows what's going wrong:
```
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/lingua-franca/lingua-franca --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/7.6.1/executionHistory/executionHistory.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/7.6.1/fileContent/fileContent.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/7.6.1/fileHashes/fileHashes.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/7.6.1/generated-gradle-jars/generated-gradle-jars.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/7.6.1/javaCompile/javaCompile.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/jars-9/jars-9.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/journal-1/journal-1.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/modules-2/modules-2.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

**Comment by lhstrh** [comment]
Looks like the Windows caching problem might be due to a bug in Gradle. I will force push this branch back to [f0bf5fd](https://github.com/lf-lang/lingua-franca/pull/1690/commits/f0bf5fd72160c811bf88e9a8d68c2ef3cb330f2f) and work on a separate branch to try and update Gradle...

**Pull request merged**
