### PR TITLE
Refactoring of the RTI implementation in the C runtime

### PR DESCRIPTION
**Pull request by ChadliaJerad**
Just to get CI running and check if the RTI refactoring breaks something.

### CODE REVIEW

**Comment by cmnrd** [comment]
I am not sure if all our workflows use the latest RTI. I think the container tests for instance use only the published version.

**Comment by lhstrh** [comment]
> I am not sure if all our workflows use the latest RTI. I think the container tests for instance use only the published version.

Yup.

**Comment by ChadliaJerad** [comment]
Thanks for the hint,  @cmnrd!
All tests that require the RTI need to build and use the latest one. The published version is useful for the releases.
And maybe have a subset of tests that pull from DockerHub.
What do you think?

**Comment by ChadliaJerad** [comment]
@petervdonovan, @lhstrh, several CIs were skipped in the latest push.
I know that this is a desired behavior you were investigating lately.
But since the commits in `reactor-c` update the RTI, this PR was meant to check if something breaks in the targets that implement federated execution using the RTI.
I think this is the case for `Python` and `TypeScript` targets.
If this does make sense, how to force `py` and `ts` CI to run? Couldn't do that by re-running the jobs.

**Comment by petervdonovan** [comment]
The "right" way to do that (without temporarily editing the `if` condition in `.github/workflows/all-targets.yml`, which actually might be the most efficient thing to do) is to manually trigger the workflows by going, for example, [here](https://github.com/lf-lang/lingua-franca/actions/workflows/only-py.yml) and using the "run workflow" dropdown on the right:
image

But this does not currently work because of a mistake in `only-py.yml`, which I will now fix.

**Comment by ChadliaJerad** [comment]
> The "right" way to do that (without temporarily editing the `if` condition in `.github/workflows/all-targets.yml`, which actually might be the most efficient thing to do) is to manually trigger the workflows by going, for example, [here](https://github.com/lf-lang/lingua-franca/actions/workflows/only-py.yml) and using the "run workflow" dropdown on the right: 

Thank you very much for the hint, @petervdonovan!

> But this does not currently work because of a mistake in `only-py.yml`, which I will now fix.

It doesn't for TypeScript either.

**Comment by ChadliaJerad** [comment]
After merging @petervdonovan's fix, both triggered Python and TypeScript CI workflows succeded ([py](https://github.com/lf-lang/lingua-franca/actions/runs/5203886045), [ts](https://github.com/lf-lang/lingua-franca/actions/runs/5203894238/jobs/9387369614)). 
This `reactor-c` [PR](https://github.com/lf-lang/reactor-c/pull/212) is then ready to be merged (modulo what will be discussed tomorrow on scheduling enclaves, I guess)...

**Comment by ChadliaJerad** [comment]
No longer needed, as the companion [`reactor-c` PR](https://github.com/lf-lang/reactor-c/pull/224) was merged.

**Pull request closed without merging**
