### PR TITLE
Enable Epoch build for M1 Mac

### PR DESCRIPTION
**Pull request by hokeun**
I propose adding ARM 64 Mac OS X as an Epoch build environment to support M1 Mac.

### CODE REVIEW

**Comment by lhstrh** [comment]
Good idea! @a-sr has a major refactoring of the build system that is basically ready to go. Let's have him decide which should go first?

**Review by edwardalee — APPROVED** [review]
Looks good to me!

**Comment by a-sr** [comment]
Since the refactoring is already done, PR #1482 will removed the changed file anyway. Hence, I would suggest to drop this PR to prevent a conflict with #1482, unless someone needs an Epoch IDE for an M1 Apple before we merge #1482.
In any case, I created an PR in the new epoch repo (https://github.com/lf-lang/epoch/pull/1) that will add M1 support for future Epoch versions.

**Review by a-sr — APPROVED** [review]

**Comment by hokeun** [comment]
Thanks, everyone! I'm not sure about the timeline for merging https://github.com/lf-lang/lingua-franca/pull/1482, but I would like to suggest merging this for now as some people (including myself and some of my students/TAs who are preparing for the embedded systems class at Hanyang) are using M1 Mac. I checked https://github.com/lf-lang/lingua-franca/pull/1482, and it seems to simply remove this pom.xml file. Thus, I think this change shouldn't block https://github.com/lf-lang/lingua-franca/pull/1482. Please let me know if this causes any conflicts, I will be happy to help and revert this.

**Pull request merged**
