### PR TITLE
Added support for state variables in diagrams

### PR DESCRIPTION
**Pull request by a-sr**
Added option to display state variables in reactors. Will be off by default.

Also includes some minor unrelated improvements in the diagrams package.

### CODE REVIEW

**Comment by lhstrh** [comment]
If we show the funny brackets we might as well show what's between them, no?

**Comment by a-sr** [comment]
I agree with @lhstrh. I don't think we should omit or replace target code.
In the end, this is an optional feature, so we do not bloat the diagram by default.

I will revise the PR accordingly; also adjusting reactor parameters to be displayed consistently.

**Comment by lhstrh** [comment]
Does anything need to change in the VS Code extension to enable this feature (besides updating the submodule)?

**Comment by a-sr** [comment]
> Does anything need to change in the VS Code extension to enable this feature (besides updating the submodule)?

No, this feature will work on both platforms out-of-the-box.
When I create a PR with changes that only work in Epoch, such as #1055, I will make sure to add a comment. Or do we want add a specific workflow, e.g. adding a dedicated label?

**Comment by lhstrh** [comment]
> > Does anything need to change in the VS Code extension to enable this feature (besides updating the submodule)?
> 
> No, this feature will work on both platforms out-of-the-box. When I create a PR with changes that only work in Epoch, such as #1055, I will make sure to add a comment. Or do we want add a specific workflow, e.g. adding a dedicated label?

That's great! What you're doing now works well. Note that we already have an `epoch` label.

**Review by cmnrd — APPROVED** [review]
Great!

**Pull request merged**
