### PR TITLE
CI formatting check disabled

### PR DESCRIPTION
**Pull request by petervdonovan**
See discussion on Zulip. People might have different opinions about this, but any decision is fine with me.

### CODE REVIEW

**Comment by lhstrh** [comment]
I agree that failures are a bit harsh (and annoying). Maybe we should print warnings in the summary instead?

**Comment by lhstrh** [comment]
Using `echo "::warning file={name},line={line},endLine={endLine},title={title}::{message}"`

**Comment by petervdonovan** [comment]
Well, if they are warnings, then they will get ignored, and they will accumulate over time -- this is what happened in the C runtime. I don't think it's a problem to strictly enforce code formatting. If it is something that people just always do (it's just one command), then it will not take much time and we will finally be able to stop talking about it.

**Comment by lhstrh** [comment]
I've just suggested an alternative approach in Zulip. It is to instate a bot that reacts to any pushes to master and applies formatting and files a PR with changes if necessary. That will get the job done and separates the formatting stuff clearly from the semantic changes.

**Comment by petervdonovan** [comment]
> I've just suggested an alternative approach in Zulip. It is to instate a bot that reacts to any pushes to master and applies formatting and files a PR with changes if necessary.

If anyone has time to set that up, then I'm all for it -- my ultimate goal is to spend less time on formatting. But I think Christian's point still stands that we do not want to make big outstanding PRs like `fed-gen` (or maybe the 6000 line PR that Shaokai has) unmergeable.

**Comment by lhstrh** [comment]
I can set it up. It going through an auxiliary PR gives us the ability to moderate and punt on formatting to accommodate outstanding PRs.

**Review by cmnrd — APPROVED** [review]
Thanks! should we merge this then?

**Pull request merged**
