### PR TITLE
Update rust runtime

### PR DESCRIPTION
**Pull request by oowekyala**
Update to use lf-lang/reactor-rs#40

### CODE REVIEW

**Comment by lhstrh** [comment]
Do we want this to be part of v0.4.0?

**Comment by lhstrh** [comment]
Do we want this to be part of v0.4.0?

**Comment by oowekyala** [comment]
@lhstrh your call. There is no new feature motivating the bump, it's just to keep in sync with refactorings of the internals.

**Review by lhstrh — APPROVED** [review]
:rocket:

**Pull request merged**
