### PR TITLE
Add `--json` and `--json-file` CLI args to Lfc

### PR DESCRIPTION
**Pull request by patilatharva**
#### Objective
Allow properties to be passed into `lfc` through a JSON string or file as an alternative to CLI arguments.

#### Reason
To provide a JSON interface between `lingo` and `lfc`.

#### Tasks
- [x] Make options {input files, `--json`, `--json-files`} mutually exclusive.
- [x] Refactor run() (entry point of `CliBase.java`) to first check for `--json` and `--json-file` args, and if either are given, unpack args and recurse into run().
- [x] Implement method `jsonStringToArgs` to convert a JSON string to a Lingua Franca args array.
- [x] Add error handling for file reads and JSON indexing.
- [x] Add tests for `--json` and `--json-file`.

### CODE REVIEW

**Comment by patilatharva** [comment]
@lhstrh this PR might take another week or so - the functionality is implemented but I can't write rigorous tests for the `--json` and `--json-file` options without building on rigorous tests for the other CLI options (i.e. the ones unpacked from JSON). So I'll be working on the latter first: #1641.

**Comment by revol-xut** [comment]
OK the let me try putting it together

**Comment by patilatharva** [comment]
@revol-xut thanks, let me know if anything breaks!

**Comment by patilatharva** [comment]
@lhstrh this PR is ready but its file diff is huge because it also contains changes from the CLI test PR #1668, so maybe we should merge that first.

**Review by lhstrh — COMMENTED** [review]
I don't think there should be any changes to the `reactor-rs` and `reactor-c` submodule in this PR...

**Comment by patilatharva** [comment]
> I don't think there should be any changes to the `reactor-rs` and `reactor-c` submodule in this PR...

Not sure how those ended up there...I'll make sure they're reverted.

**Comment by lhstrh** [comment]
@patilatharva, after merging your other PR, there are some conflicts with this branch. Could you please fix these? After that, we should be able to merge PR as well...

**Pull request closed without merging**
