### PR TITLE
naming banked reactors

### PR DESCRIPTION
**Pull request by OmerMajNition**
https://github.com/lf-lang/lingua-franca/issues/2319 has the description of the problem addressed with this PR

### CODE REVIEW

**Comment by cmnrd** [comment]
I am not entirely sure what this tries to achieve. Is this about getting the fully qualified names of reactors? I think we already provide functionality for that, also in the C target.

**Comment by cmnrd** [comment]
@petervdonovan Could you comment on this? Are there FQNs available in C, and how are they exposed?

**Comment by petervdonovan** [comment]
> Are there FQNs available in C, and how are they exposed?

If they are available in the C target, I am not aware of them, and after looking briefly I do not see them in the source code (in particular, there is no `name` field in the `self_base_t` struct defined [here](https://github.com/lf-lang/reactor-c/blob/76408229db1e096d586f96eb7ea5259de6405220/include/core/lf_types.h#L276).

It looks like this PR adds FQNs without requiring any extension of `self_base_t` when the `name` field is not used, so I think we might as well merge it. CI is failing, but I think that should be easily fixed.

**Comment by cmnrd** [comment]
Ok. I still don't understand what the PR does, though. @OmerMajNition could you add some explanation? Is the idea to introduce a magic parameter `name` that gets automatically assigned the FQN?

**Comment by OmerMajNition** [comment]
@cmnrd , I've added further description in GH-Issue: https://github.com/lf-lang/lingua-franca/issues/2319. Please let me know if we need further clarification.

**Comment by edwardalee** [comment]
I believe this is fixed in a better way with #2450 .

**Pull request closed without merging**
