### PR TITLE
Upstream connection delays now properly handled in the TypeScript federates

### PR DESCRIPTION
**Pull request by byeong-gil**
The previous version of this PR is [lingua-franca/pull/1344](https://github.com/lf-lang/lingua-franca/pull/1344)

Relevant reactor-ts PR: [reactor-ts/#138](https://github.com/lf-lang/reactor-ts/pull/138)

This PR adds upstream connection delays in the generated TypeScript federate files.

### CODE REVIEW

**Comment by byeong-gil** [comment]
It seems like there is a problem with handling `after` delays in docker. The test [TypeScript/src/docker/federated/DistributedCountContainerized.lf](https://github.com/lf-lang/lingua-franca/blob/master/test/TypeScript/src/docker/federated/DistributedCountContainerized.lf) fails. I'll turn this PR into a draft.

**Comment by petervdonovan** [comment]
Apparently the federates are not even being built because something in the generated code does not type check
```
    ERROR: never[]; }' is not assignable to type 'FederateConfig'. [c.ts:17:280]
    ERROR: never[]; }' is not assignable to type 'FederateConfig'. [c.ts:17:280]
    ERROR: TimeValue[][]; }' is not assignable to type 'FederateConfig'. [p.ts:17:294]
    ERROR: TimeValue[][]; }' is not assignable to type 'FederateConfig'. [p.ts:17:294]
```

**Comment by byeong-gil** [comment]
That's weird... Because I cannot find any error on my local computer when I compile and run the test `test/TypeScript/src/docker/federated/DistributedCountContainerized`.
The CI is run with a `master` branch of the `reactor-ts`, right? If it is, there will be no type check error.

**Comment by petervdonovan** [comment]
I was able to reproduce the problem. In my local clone of `reactor-ts` (in my case, located at `/home/peter/lf/reactor-ts`), I checked out `ts-common-timevalue`, and in my local clone of `lingua-franca`, I checked out `ts-upstream-delays`. Then I ran the command 
```
lfc --external-runtime-path /home/peter/lf/reactor-ts test/TypeScript/src/docker/federated/DistributedCountContainerized.lf 
```

and was able to reproduce the problem. Maybe double check to make sure that you passed the correct path to LFC using `--external-runtime-path`?

**Review by lhstrh — APPROVED** [review]
Looks OK to me, but it was marked as "draft" so it escaped my attention. Could you please add JavaDoc to the new function that you added in `TSExtension`? Thanks!

**Pull request merged**
