### PR TITLE
Use path, not URI in line-directives (#1407)

### PR DESCRIPTION
**Pull request by erlingrj**
Addressing #1407

### CODE REVIEW

**Review by edwardalee — APPROVED** [review]
LGTM.  Does this correctly report errors on the right line in Epoch?

**Comment by cmnrd** [comment]
Also I am wondering how this affects error reporting via the LSP and on the command line in lfc. Tagging @petervdonovan

**Comment by erlingrj** [comment]
I am away for a week. I'm not sure how this affects Epoch or LSP.

**Review by petervdonovan — APPROVED** [review]
I think we can merge this now. Thanks Erling!

**Pull request merged**
