### PR TITLE
Clean up unnecessary xtext dependencies in LFUiModuleImpl.java and delete InitializeRemoteTriggersTable.xtend

### PR DESCRIPTION
**Pull request by hokeun**

### CODE REVIEW

**Review by petervdonovan — APPROVED** [review]
This looks good to me!

**Review by lhstrh — COMMENTED** [review]
The changes look good to me, but is it OK to ditch `InitializeRemoteTriggersTable`, @edwardalee?

**Comment by edwardalee** [comment]
Yes, InitializeRemoteTriggersTable is obsolete. I missed that.

**Review by edwardalee — APPROVED** [review]
I am completely unfamiliar with LFUiModuleImpl, so I can't really offer any opinion, but I don't see any red flags with the changes.

**Comment by hokeun** [comment]
> Yes, InitializeRemoteTriggersTable is obsolete. I missed that.

Thank you for confirming!

**Comment by hokeun** [comment]
Thank you everyone for reviewing this PR!

**Pull request merged**
